### ISSUE TITLE
Using kubectl to Create an ELB Ingress

### ISSUE THREAD

**Issue by stevek-pro** [opentelekomcloud-docs/cloud-container-engine#31]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/umn/source/networking/ingress/using_kubectl_to_create_an_elb_ingress.rst

Shouldn't some of these docs be updated for latest Kubernetes versions? 

It's doubtful that the code from the docs will work with Kubernetes 1.21 or 1.23, the current versions of non-turbo CCE.

Ie.:

`---`
```
        backend:
          serviceName: <your_service_name>  # Replace it with the name of your target Service.
          servicePort: 80
```

`+++`
```
        backend:
          service:
             name: <your_service_name>  # Replace it with the name of your target Service.
             port: 
                number: 80
```

or:

`-`
`apiVersion: networking.k8s.io/v1beta1`

`+`
`apiVersion: networking.k8s.io/v1`

or:

`---`
```
annotations:
    kubernetes.io/ingress.class: cce
```

`+++`
```
spec:
  ingressClassName: cce
```
